import type { Metadata } from "next";
import { Grand_Hotel, Luckiest_Guy, Aleo } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Wpp from "@/components/subc/Wpp";

const grandHotel = Grand_Hotel({ weight: "400", subsets: ["latin"], variable: "--font-grand-hotel", display: "swap" });
const luckiestGuy = Luckiest_Guy({ weight: "400", subsets: ["latin"], variable: "--font-luckiest-guy", display: "swap" });
const aleo = Aleo({ weight: ["300", "400", "700"], subsets: ["latin"], variable: "--font-aleo", display: "swap" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="pt-BR">
      <body
        className={[

          grandHotel.variable,
          luckiestGuy.variable,
          aleo.variable,
          "antialiased min-h-screen flex flex-col",
        ].join(" ")}
      >
        <Header />
        <Wpp />
        <main className="flex-1">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
